demo/application/urls.py
from django.urls import path
from . import views


app_name = 'application'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('application/', include('application.urls')),
    path('', include('homepage.urls')),
]

demo/homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
]

demo/application/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

demo/homepage/models.py
from django.db import models

# Create your models here.

demo/application/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join(f"&laquo;{q.question_text}&raquo;" for q in latest_question_list)

    return render(
        request,
        "application/index.html",
        {
            'latest_question_list': latest_question_list
        }
    )


def detail(request, question_id):
    question = Question.objects.filter(pk=question_id).first()
    if question:
        response = render(
            request,
            "application/detail.html",
            {
                "question": question,
            }
        )
    else:
        raise Http404("Вопрос не существует.")

    return response


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(
        request,
        "application/results.html",
        {
            'question': question
        }
    )


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    selected_choice = question.choice_set.filter(pk=request.POST.get('choice')).first()
    if selected_choice:
        selected_choice.votes += 1
        selected_choice.save()
        response = HttpResponseRedirect(
            reverse('application:results', args=(question.id, ))
        )
    else:
        response = render(
            request,
            "application/detail.html",
            {
                'question': question,
                'error_message': 'Вы не выбрали вариант ответа.'
            }
        )

    return response

demo/homepage/views.py
from django.shortcuts import render


def index(request):
    return render(
        request,
        "homepage/index.html"
    )

demo/templates/application/detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Опросы</title>
</head>
<body>

    <form action="{% url 'application:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Проголосовать">
    </form>

</body>
</html>

demo/templates/application/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Опросы</title>
</head>
<body>

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'application:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных опросов.</p>
    {% endif %}

</body>
</html>

demo/templates/application/results.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Опросы</title>
</head>
<body>

    <h1>{{ question.question_text }}</h1>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} &mdash; {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}

</body>
</html>

demo/templates/homepage/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сайт про разное</title>
</head>
<body>

    <h1>Разделы</h1>
    <ul>
        <li><a href="{% url 'application:index' %}">Опросы</a></li>
    </ul>

</body>
</html>